from pptx import Presentation
from pptx.util import Inches, Pt
import os
import requests
from io import BytesIO

def create_ppt(data, filename="generated_presentation.pptx", image_mode=None):
    """
    Creates a PowerPoint presentation from structured data.
    
    Args:
        data (dict): Dictionary usually containing 'title' and 'slides' list.
                     Each slide in 'slides' should have 'heading' and 'bullet_points'.
        filename (str): Name of the output file.
        image_mode (str): 'no_image', 'manual', or 'auto'
        
    Returns:
        str: Absolute path to the generated PPTX file.
    """
    prs = Presentation()

    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = data.get("title", "Untitled Presentation")
    subtitle.text = "Generated by Gemini"

    # 2. Content Slides
    # Layout 1: Title and Content (Standard)
    # Layout 3: Two Content (Title, Left Content, Right Content) -> Used for Images
    
    for slide_data in data.get("slides", []):
        
        use_image_layout = image_mode in ['manual', 'auto']
        
        if use_image_layout:
             slide_layout = prs.slide_layouts[3] # Two Content
        else:
             slide_layout = prs.slide_layouts[1] # Title and Content

        slide = prs.slides.add_slide(slide_layout)
        shapes = slide.shapes

        # Title
        title_shape = shapes.title
        title_shape.text = slide_data.get("heading", "No Title")

        # Body (Bullet points)
        # In Layout 1, body is placeholders[1]
        # In Layout 3, left body is placeholders[1]
        
        body_shape = shapes.placeholders[1]
        tf = body_shape.text_frame
        tf.word_wrap = True

        # Content (Left Column or Main Body)
        # Handle new 'content' structure or fallback to 'bullet_points'
        content = slide_data.get("content", [])
        if not content and "bullet_points" in slide_data:
            # Backwards compatibility / Fallback
            content = [{"text": bp, "level": 0} for bp in slide_data["bullet_points"]]

        if content:
            for i, item in enumerate(content):
                text = item.get("text", "")
                level = item.get("level", 0)
                
                if i == 0:
                    p = tf.text = text 
                    p = tf.paragraphs[0]
                else:
                    p = tf.add_paragraph()
                    p.text = text

                p.level = level
                
                # Typography & Overflow Handling
                if level == 0:
                    p.font.size = Pt(22)
                else:
                    p.font.size = Pt(18)
                
                # Add some spacing
                p.space_after = Pt(10)
             
        # Image Handling (Right Column)
        if use_image_layout:
            # placeholders[2] is the right column in Layout 3
            image_placeholder = shapes.placeholders[2]
            
            if image_mode == 'auto':
                query = slide_data.get("image_search_query", slide_data.get("heading", "image"))
                # Fallback if query is None or empty
                if not query:
                    query = "placeholder"
                    
                # Fetch placeholder image
                try:
                    # Using placehold.co for dynamic placeholder images
                    # Sanitize query for URL
                    import urllib.parse
                    safe_query = urllib.parse.quote(query)
                    image_url = f"https://placehold.co/600x400?text={safe_query}"
                    
                    response = requests.get(image_url)
                    if response.status_code == 200:
                        image_stream = BytesIO(response.content)
                        # Insert picture into the placeholder
                        image_placeholder.insert_picture(image_stream)
                    else:
                        print(f"Failed to fetch image for {query}: {response.status_code}")
                except Exception as e:
                    print(f"Error fetching image: {e}")
            
            # If 'manual', we just leave the placeholder empty. 
            # In PPTX, an empty placeholder behaves like a content box where user can click to add content.

    # Ensure output directory exists
    output_path = os.path.abspath(filename)
    prs.save(output_path)
    return output_path
